# Site settings
email:
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: JA Notes
description: A quiet place to reflect about tech
url: ""
twitter_username:
default_img:

# Profile settings
name: Jorge Andre
profile_img: https://scontent.ftpe3-1.fna.fbcdn.net/v/t1.0-9/12143247_10208314082197474_6797702917728691628_n.jpg?oh=bc8511b76273dd698d5ebbc7ccfa05ef&oe=590173DD
profile: Curious by nature
social:
  github: https://github.com/jokandre

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
